volumes:
  frontend_dist:
  caddy_data:
  caddy_config:

services:
  frontend:
    image: molevolvr-frontend
    build:
      context: ./frontend
      target: release
    volumes:
      - frontend_dist:/app/frontend/dist
    depends_on:
      - backend
  
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_dist:/srv
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
